name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Display Date
        run: | 
          date
      - name: Display List
        run: |
          ls --a
